name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build macOS Application
        uses: starburst997/build-macos@v1.0.7
        with:
          project_path: "Dust.xcodeproj"
          scheme: "Dust"
          output_name: "Dust"
          mac_bundle_id: "com.Yuki.Dust"
          build_signed: false
